/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FortranExecuter */

#ifndef _Included_FortranExecuter
#define _Included_FortranExecuter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FortranExecuter
 * Method:    computexmldata
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_FortranExecuter_computexmldata
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
